# Generated by Django 3.0.2 on 2020-02-26 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='default_work_time',
            field=models.PositiveIntegerField(default=80, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_apr',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_aug',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_dec',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_feb',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_jan',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_jul',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_jun',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_mar',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_may',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_nov',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_oct',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='worktimemodel',
            name='part_time_sep',
            field=models.PositiveIntegerField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
