# Generated by Django 3.0.2 on 2020-02-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_share', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('project_partner', models.CharField(max_length=1000)),
                ('goal', models.CharField(max_length=1000)),
                ('milestones', models.CharField(max_length=1000)),
                ('short_description', models.CharField(max_length=1000)),
                ('plant_name', models.CharField(max_length=1000)),
                ('funding', models.CharField(max_length=1000)),
                ('tools', models.CharField(max_length=1000)),
                ('budget', models.PositiveIntegerField()),
                ('funding_type', models.CharField(choices=[('kdc', 'KDC'), ('ktc', 'KTC'), ('od', 'OD')], default='kdc', max_length=3)),
                ('project_leader', models.CharField(max_length=1000)),
                ('report', models.CharField(max_length=1000)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('cost_center', models.CharField(max_length=1000)),
                ('project_stage', models.CharField(choices=[('planned', 'planned'), ('started', 'started'), ('modeling_complete', 'modeling complete'), ('report_finished', 'report finished')], default='planned', max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyWorkload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('workload_jan', models.PositiveIntegerField(default=0, null=True)),
                ('workload_feb', models.PositiveIntegerField(default=0, null=True)),
                ('workload_mar', models.PositiveIntegerField(default=0, null=True)),
                ('workload_apr', models.PositiveIntegerField(default=0, null=True)),
                ('workload_may', models.PositiveIntegerField(default=0, null=True)),
                ('workload_jun', models.PositiveIntegerField(default=0, null=True)),
                ('workload_jul', models.PositiveIntegerField(default=0, null=True)),
                ('workload_aug', models.PositiveIntegerField(default=0, null=True)),
                ('workload_sep', models.PositiveIntegerField(default=0, null=True)),
                ('workload_oct', models.PositiveIntegerField(default=0, null=True)),
                ('workload_nov', models.PositiveIntegerField(default=0, null=True)),
                ('workload_dec', models.PositiveIntegerField(default=0, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='projects.Contributor')),
            ],
        ),
    ]
