# Generated by Django 3.0.2 on 2020-02-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200226_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('active', 'active member of the group'), ('inactive', 'former member of the group')], default='active', max_length=8),
        ),
    ]
